[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
